server:
  port: 20000

spring:
  application:
    name: eureka-client
  cloud:
    discovery:
      # 该client是否可以进行注册和发现
      enabled: true
  profiles:
    active: eureka-default

info:
  app.name: spring-cloud-eureka-client
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$