eureka:
  instance:
    app-name: eureka-client-provider-1
    instance-id: eureka-client-provider-1-zone_1-${server.port}-${random.value}
    metadata-map:
      zone: zone_1
    # 访问路径可以显示IP地址
    prefer-ip-address: false
    status-page-url-path: /info
    health-check-url-path: /health
    # 服务续约时间
    lease-renewal-interval-in-seconds: 30
    # 服务失效时间
  #    lease-expiration-duration-in-seconds: 90

  client:
    region: shanghai
    availability-zones:
      shanghai: zone_1
    # 禁止该client被注册，跟注册中心脱离关系
    enabled: true
    # 健康检查
    healthcheck:
      enabled: true
    # 是否允许将该实例注册到server中以供其他服务发现
    register-with-eureka: true
    # 是否允许获取注册表信息
    fetch-registry: true
    # 缓存的服务注册信息定期更新时间间隔
    registry-fetch-interval-seconds: 40
    service-url:
      zone_1: http://eureka-server-5:10005/eureka/