server:
  port: 22000

logging:
  level:
    root: info

project:
  name: alibaba-nacos-config-demo-native
  id: nacos-demo-native

management:
  endpoints:
    web:
      exposure:
        include: '*'