logging:
  level:
    root: info

spring:
  application:
    name: z2huo-spring-cloud-eureka-server

server:
  port: 10000

eureka:
  instance:
    app-name: localhost
    # 服务失效时间
    lease-expiration-duration-in-seconds: 90
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 自我保护机制
    enable-self-preservation: true
    # 自我保护系数
    renewal-percent-threshold: 0.9
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 自己时注册中心，职责是维护服务示例，不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.app-name}:${server.port}/eureka/