server:
  port: 10200

logging:
  level:
    root: info

eureka:
  instance:
    app-name: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 自我保护机制
    enable-self-preservation: true
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 自己时注册中心，职责是维护服务示例，不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.app-name}:${server.port}