eureka:
  instance:
    app-name: eureka-server
    instance-id: eureka-server-${server.port}-${random.value}
    # 服务失效时间
    lease-expiration-duration-in-seconds: 90
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 自我保护机制
    enable-self-preservation: true
    # 自我保护系数
    renewal-percent-threshold: 0.9
    # 节点更新频率
    peer-eureka-nodes-update-interval-ms: 600000
    # 定期检测失效服务的时间
    eviction-interval-timer-in-ms: 80000
    # 获取注册表时是否从ReadOnlyCacheMap中获取
    use-read-only-response-cache: true
    # ReadWriteCacheMap向ReadOnlyCacheMap同步的时间间隔
    response-cache-update-interval-ms: 20000
  client:
    # 是否向注册中心注册自己
    register-with-eureka: false
    # 自己是注册中心，职责是维护服务示例，不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/