server:
  port: 23000

logging:
  level:
    root: info

spring:
  application:
    name: alibaba-consumer-1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
#        endpoint: alibaba-consumer-1

    loadbalancer:
      nacos:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'